### ISSUE TITLE
Test Realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [HanjiangHu/DIFL-FCL#1]
How do I test it realtime?

**Comment by HanjiangHu** [comment]
First you should choose the closest domain from the environments (foliage, weather, season, etc.) of CMU Seasons dataset (see CMU-Seasons readme.md for details) for your own database and query images. Then use the pre-trained model of the corresponding domain to test it. Note that make sure the sequential correspondences of the domains for your own images folders and the pre-trained models are correct. 

For the real-time loop closure for long-term SLAM, maybe the database images are the keyframes of the map and some efficient matching strategy should be implemented instead of the brute-force retrieval for every query image.

**Comment by Zumbalamambo** [comment]
@HanjiangHu  thank you! could you please tell me how i can prepare my own dataset?

**Comment by HanjiangHu** [comment]
@Zumbalamambo Once the database images (with poses) and query images (take 3 different query conditions for example) are collected, the database folder is named as _test00_ for reference condition while query folders are named as _test01_, _test02_, _test03_. Then the pre-models on CMU Seasons database are chosen and renamed based on the most similar environmental conditions for all the database and query conditions, e.g. the condition of **Overcast + Foliage** on CMU is chosen for your own folder _test01_ under similar **overcast** with **foliage** condition, then the pre-trained model should be renamed from _600_net_G11.pth_ to _600_net_G01.pth_, from _600_net_D11.pth_ to _600_net_D01.pth_, and from _600_net_G23.pth_ to _600_net_G05.pth_. Similarly, for _test00_, _test02_, _test03_, the pre-trained models are chosen and renamed, resulting in 3 pre-trained models for every test condition from _test00_ to _test03_, i.e. _600_net_G00.pth, 600_net_G01.pth, 600_net_G02.pth, 600_net_G03.pth, 600_net_D00.pth, 600_net_D01.pth, 600_net_D02.pth, 600_net_D03.pth, 600_net_G04.pth, 600_net_G05.pth, 600_net_G06.pth, 600_net_G07.pth._ Note that the option in the test command **--n_domains** should be 4 since there are 4 different domains including database in the example. Also, maybe some necessary changes are expected in the code but I believe it’s not hard to fix these obvious bugs. Good luck with your own test and feel free to contact me if there’s any problem. BTW I have tested these pre-trained models on the RobotCar dataset in the above way and it works well.
